language: node_js
node_js:
  - "0.12"

branches:
  only:
    - master

before_install:
  - npm install bower -g
  - npm install gulp -g

script:
  - npm install
  - bower install

cache:
  directories:
  - bower_components
  - node_modules

notifications:
  email:
    - luka.jerkovic@sistemi.hr

